[package]
name = "ddos"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1"
log = "0.3"
env_logger = "0.4.0"
rustc-serialize = "0.3"
docopt = "0.7"
rustls = "0.16"
webpki = "0.21"
webpki-roots = "0.18"
